spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 100MB

  web:
    resources:
      static-locations: file:${APPLICATION_FILE_UPLOADS_MEDIA_OUTPUT_PATH}

springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      media-output-path: ${APPLICATION_FILE_UPLOADS_MEDIA_OUTPUT_PATH}
    base-url: ${BASE_URL}

  jwt:
    secret: ${APPLICATION_JWT_SECRET}
    expiration: ${APPLICATION_JWT_EXPIRATION}
